/*
 *      Version numbering for LAME.
 *
 *      Copyright (c) 1999 A.L. Faber
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/*!
  \file   version.c
  \brief  Version numbering for LAME.

  Contains functions that describe the version of LAME. The group
  \ref api_version describes what each form is for.

  \author A.L. Faber
  \version \$Id$
*/

/* Every function below is part of that interface, so the group is opened once
   here rather than named on each of them. Text inside the \addtogroup block
   would be appended to the group's description, so keep this comment out of
   it. */
/*! \addtogroup api_version
    @{ */


#ifdef HAVE_CONFIG_H
# include <config.h>
#endif


#include "lame.h"
#include "machine.h"

#include "version.h"    /* macros of version numbers */

#ifdef HAVE_VCSREVISION_H
# include "vcsrevision.h"  /* LAME_VCS_REVISION, generated by the build */
#endif

#ifdef LAME_VCS_REVISION
# define LAME_VCS_REVISION_SUFFIX " " LAME_VCS_REVISION
#else
# define LAME_VCS_REVISION_SUFFIX ""
#endif





/*! Get the LAME version string. */
/*!
  The full form, for display. For an alpha or beta build it contains the build
  date, and for an alpha also the build time. So two builds of the same source
  can give different strings. An alpha or beta build from a Subversion or git
  working copy also names the revision of that working copy.

  The layout is not guaranteed. To compare versions, use
  \c get_lame_version_numerical(). To write a version into an encoded stream,
  use \c get_lame_short_version(), which is the same for every build.

  \return a static string that describes the version of LAME, never NULL. It
          belongs to the library, so do not free or change it. It is valid as
          long as the process runs.
*/
const char *
get_lame_version(void)
{                       /* primary to write screen reports */
    /* Here we can also add informations about compile time configurations */

#if   LAME_ALPHA_VERSION
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) " "
        "(alpha " STR(LAME_PATCH_VERSION) LAME_VCS_REVISION_SUFFIX ", "
        __DATE__ " " __TIME__ ")";
#elif LAME_BETA_VERSION
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) " "
        "(beta " STR(LAME_PATCH_VERSION) LAME_VCS_REVISION_SUFFIX ", "
        __DATE__ ")";
#elif LAME_RELEASE_VERSION && (LAME_PATCH_VERSION > 0)
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) "." STR(LAME_PATCH_VERSION);
#else
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION);
#endif

    return str;
}


/*! Get the short LAME version string. */
/*!
  The same version as \c get_lame_version(), without the build date and time.
  So two builds of the same source give the same string. This makes it the
  form to write into an encoded stream, and keeps the output of the encoder
  reproducible.

  \return a static string that holds the version of LAME, never NULL. It
          belongs to the library, so do not free or change it. It is valid as
          long as the process runs.
*/
const char *
get_lame_short_version(void)
{
    /* adding date and time to version string makes it harder for output
       validation */

#if   LAME_ALPHA_VERSION
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) " (alpha " STR(LAME_PATCH_VERSION) ")";
#elif LAME_BETA_VERSION
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) " (beta " STR(LAME_PATCH_VERSION) ")";
#elif LAME_RELEASE_VERSION && (LAME_PATCH_VERSION > 0)
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) "." STR(LAME_PATCH_VERSION);
#else
    static /*@observer@ */ const char *const str =
        STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION);
#endif

    return str;
}

/*! Get the _very_ short LAME version string. */
/*!
  The shortest form: `"LAME"`, the major and minor version, a one-character
  build type (`'a'` alpha, `'b'` beta, `'r'` a patched release, `' '`
  otherwise), and for a patched release the patch level. It is for a caller
  with very little room. The library does not use it. The encoder writes its
  version into the LAME tag with a separate internal function, whose width is
  fixed for binary compatibility.

  This string has **no guaranteed maximum length**. It grows with the version
  numbers. So a caller that copies it into a field of fixed size must limit
  the copy itself.

  \return a static string that holds the version of LAME, never NULL. It
          belongs to the library, so do not free or change it. It is valid as
          long as the process runs.
*/
const char *
get_lame_very_short_version(void)
{
    /* adding date and time to version string makes it harder for output
       validation */
#if   LAME_ALPHA_VERSION
#define P "a"
#elif LAME_BETA_VERSION
#define P "b"
#elif LAME_RELEASE_VERSION && (LAME_PATCH_VERSION > 0)
#define P "r"
#else
#define P " "
#endif
    static /*@observer@ */ const char *const str =
#if (LAME_PATCH_VERSION > 0)
      "LAME" STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) P STR(LAME_PATCH_VERSION)
#else
      "LAME" STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) P
#endif
      ;
    return str;
}

/*!
  \internal
  Get the encoder version string written into the LAME tag.

  It is not part of the public API. It is not exported, and the tag format
  fixes the field that it fills. A program that needs a short version string
  uses \c get_lame_very_short_version().

  The string has at most 9 characters. It must start with "LAME", because
  some hardware and software decoders check for it.

  \par Field width and format (fixed, critical for binary compatibility)
  This string is copied into a **fixed 9-byte** field of the LAME tag, which
  is in every encoded MP3 stream (see \c VbrTag.c, \c LAMEHEADERSIZE and the
  \c strncpy(...,9) call in the code that writes the tag). A wider field
  would move every later byte of the tag, and break every decoder that reads
  the tag at a fixed offset. So the width cannot change. The format
  (`"LAME" major "." minor type`) is fixed for the same reason, because some
  decoders reportedly match on it.

  \par Byte budget
  `strlen("LAME")` (4) + `strlen(major)` + `strlen(".")` (1) +
  `strlen(minor)` + `strlen(type)` (1, always one character:
  `'a'`/`'b'`/`'r'`/`' '`) must not be more than 9, that is:
  \code
      strlen(major) + strlen(minor) <= 3
  \endcode
  A compile-time check right below this function enforces this
  (`compiletime_assert`). If it fails, change the version numbers, not the
  width or the format of this field.

  \return the short version string.
 */
const char*
get_lame_tag_encoder_short_version(void)
{
    static /*@observer@ */ const char *const str =
            /* FIXME: new scheme / new version counting / drop versioning here ? */
    "LAME" STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) P
    ;
    return str;
}

/*! \internal
 *  Checks the byte budget above at compile time. It fails at the version
 *  change that breaks the budget, instead of cutting the string without a
 *  message at run time. */
compiletime_assert(sizeof("LAME" STR(LAME_MAJOR_VERSION) "." STR(LAME_MINOR_VERSION) P) - 1 <= 9);

/*! Get the version string for GPSYCHO. */
/*!
  GPSYCHO is the psychoacoustic model that LAME uses. It has its own version,
  which changes separately from the version of LAME. As with
  \c get_lame_version(), an alpha or beta build contains the build date, so
  the string cannot be compared. \c get_lame_version_numerical() returns the
  same numbers in a form that can be compared.

  \return a static string that describes the version of GPSYCHO, never NULL.
          It belongs to the library, so do not free or change it. It is valid
          as long as the process runs.
*/
const char *
get_psy_version(void)
{
#if   PSY_ALPHA_VERSION > 0
    static /*@observer@ */ const char *const str =
        STR(PSY_MAJOR_VERSION) "." STR(PSY_MINOR_VERSION)
        " (alpha " STR(PSY_ALPHA_VERSION) ", " __DATE__ " " __TIME__ ")";
#elif PSY_BETA_VERSION > 0
    static /*@observer@ */ const char *const str =
        STR(PSY_MAJOR_VERSION) "." STR(PSY_MINOR_VERSION)
        " (beta " STR(PSY_BETA_VERSION) ", " __DATE__ ")";
#else
    static /*@observer@ */ const char *const str =
        STR(PSY_MAJOR_VERSION) "." STR(PSY_MINOR_VERSION);
#endif

    return str;
}


/*! Get the URL for the LAME website. */
/*!
  Fixed when the library is built. A program that reports the encoder can
  point its users to the project, without writing an address into its own
  code that may change.

  \return a static string that holds the URL of the project, never NULL. It
          belongs to the library, so do not free or change it. It is valid as
          long as the process runs.
*/
const char *
get_lame_url(void)
{
    static /*@observer@ */ const char *const str = LAME_URL;

    return str;
}


/*! Get the numerical representation of the version. */
/*!
  Everything that the version strings contain, as integers that can be
  compared: the version of LAME and the version of the psychoacoustic model,
  each as separate numbers. So a caller can test for a minimum version
  without parsing text.

  \c alpha and \c beta hold the patch level of an alpha or beta build, and
  are 0 otherwise. At most one of them is non-zero. \c features stays for
  compatibility and is always the empty string. Make no assumptions about its
  content.

  \code
      lame_version_t v;
      get_lame_version_numerical(&v);
      if (v.major > 3 || (v.major == 3 && v.minor >= 100)) {
          / * a 3.100-or-later feature is available * /
      }
  \endcode

  \param lvp  the structure to fill in. It must not be NULL. The function
              always writes it and sets every field, so it does not need to
              be initialized first.
*/
void
get_lame_version_numerical(lame_version_t * lvp)
{
    static /*@observer@ */ const char *const features = ""; /* obsolete */

    /* generic version */
    lvp->major = LAME_MAJOR_VERSION;
    lvp->minor = LAME_MINOR_VERSION;
#if LAME_ALPHA_VERSION
    lvp->alpha = LAME_PATCH_VERSION;
    lvp->beta = 0;
#elif LAME_BETA_VERSION
    lvp->alpha = 0;
    lvp->beta = LAME_PATCH_VERSION;
#else
    lvp->alpha = 0;
    lvp->beta = 0;
#endif

    /* psy version */
    lvp->psy_major = PSY_MAJOR_VERSION;
    lvp->psy_minor = PSY_MINOR_VERSION;
    lvp->psy_alpha = PSY_ALPHA_VERSION;
    lvp->psy_beta = PSY_BETA_VERSION;

    /* compile time features */
    /*@-mustfree@ */
    lvp->features = features;
    /*@=mustfree@ */
}


/*! Get the pointer width the library was built for. */
/*!
  Describes the build, not the operating system. It comes from the size of a
  pointer in the library, so a 32-bit library on a 64-bit system returns 32
  bits. It is meant for a version line next to \c get_lame_version().

  \return \c "32bits" or \c "64bits", or the empty string on a target whose
          pointers are neither 4 nor 8 bytes wide. Never NULL. The string
          belongs to the library, so do not free or change it.
*/
const char *
get_lame_os_bitness(void)
{
    static /*@observer@ */ const char *const strXX = "";
    static /*@observer@ */ const char *const str32 = "32bits";
    static /*@observer@ */ const char *const str64 = "64bits";

    switch (sizeof(void *)) {
    case 4:
        return str32;

    case 8:
        return str64;

    default:
        return strXX;
    }
}

/*! @} */

/* end of version.c */
